name: matrix1c
on: workflow_dispatch
jobs:
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: foo
            config: Debug
          - project: bar
            config: Release
    steps:
      - run: echo "Matrix - Project ${{ matrix.project }}, Config ${{ matrix.config }}"
