name: sqlite
on: workflow_dispatch
jobs:
  show-vers-num:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.14
      - run: python -c "import sqlite3; print(sqlite3.sqlite_version)"
